# Generated by Django 4.2.20 on 2025-04-30 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=100)),
                ('passport', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('quick_notes', models.TextField(blank=True)),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('trekking', models.BooleanField(default=False)),
                ('peak_climbing', models.BooleanField(default=False)),
                ('tour', models.BooleanField(default=False)),
                ('adventure_day_activities', models.BooleanField(default=False)),
                ('flight', models.BooleanField(default=False)),
                ('misc_service', models.CharField(blank=True, max_length=100)),
                ('guide', models.CharField(blank=True, max_length=100)),
                ('porter', models.CharField(blank=True, max_length=100)),
                ('package', models.CharField(blank=True, max_length=100)),
                ('transport', models.CharField(blank=True, max_length=100)),
                ('accommodation', models.CharField(blank=True, max_length=100)),
                ('number_of_days', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('additional_charges', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notification_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['starting_date'],
            },
        ),
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_items', to='clients.client')),
            ],
        ),
    ]
