# Generated by Django 4.2.20 on 2025-04-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='number_of_days',
        ),
        migrations.AddField(
            model_name='client',
            name='total_days',
            field=models.IntegerField(default=1, help_text='Total days of service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='trekking_days',
            field=models.IntegerField(blank=True, help_text='Number of actual trekking/climbing days', null=True),
        ),
    ]
