# Generated by Django 5.1.5 on 2025-01-19 10:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrekkingExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('trekking_route', models.CharField(max_length=200)),
                ('duration_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('trekking_guide', models.CharField(max_length=100)),
                ('assistant_guide', models.CharField(blank=True, max_length=100, null=True)),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('package_rate', models.IntegerField(blank=True, null=True)),
                ('package_numbers', models.IntegerField(blank=True, null=True)),
                ('package_days', models.IntegerField(blank=True, null=True)),
                ('guide_salary_rate', models.IntegerField(blank=True, null=True)),
                ('guide_salary_days', models.IntegerField(blank=True, null=True)),
                ('porter_salary_rate', models.IntegerField(blank=True, null=True)),
                ('porter_numbers', models.IntegerField(blank=True, null=True)),
                ('porter_days', models.IntegerField(blank=True, null=True)),
                ('assistant_guide_salary_rate', models.IntegerField(blank=True, null=True)),
                ('assistant_guide_days', models.IntegerField(blank=True, null=True)),
                ('extra_expenses', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('advance_paid', models.IntegerField(default=0)),
                ('balance_amount', models.IntegerField(default=0)),
                ('received_by', models.CharField(max_length=100)),
                ('approved_by', models.CharField(max_length=100)),
                ('paid_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn_no', models.IntegerField(help_text='Serial Number (e.g., 5, 6)')),
                ('particular', models.CharField(max_length=200)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('numbers', models.IntegerField(blank=True, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
                ('total_amount', models.IntegerField()),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('trekking_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_expenses', to='treks.trekkingexpense')),
            ],
            options={
                'ordering': ['sn_no'],
            },
        ),
    ]
