# Generated by Django 4.2.20 on 2025-04-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trekkingexpense',
            name='guide_names',
            field=models.TextField(blank=True, help_text='Names of additional guides, one per line'),
        ),
        migrations.AddField(
            model_name='trekkingexpense',
            name='porter_names',
            field=models.TextField(blank=True, help_text='Names of porters, one per line'),
        ),
    ]
