# Generated by Django 4.2.20 on 2025-04-19 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0002_trekkingexpense_guide_names_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Porter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trekking_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='porters', to='treks.trekkingexpense')),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(default='Guide', max_length=50)),
                ('trekking_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='treks.trekkingexpense')),
            ],
        ),
    ]
