# Generated by Django 4.2.20 on 2025-04-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0003_porter_guide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trekkingexpense',
            name='guide_names',
        ),
        migrations.RemoveField(
            model_name='trekkingexpense',
            name='porter_names',
        ),
        migrations.AddField(
            model_name='guide',
            name='salary_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='salary_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='porter',
            name='salary_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='porter',
            name='salary_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
