# Generated by Django 4.2.20 on 2025-04-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0004_remove_trekkingexpense_guide_names_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trekkingexpense',
            name='guide_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trekkingexpense',
            name='guide_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
