# Generated by Django 4.2.20 on 2025-04-19 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0005_trekkingexpense_guide_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(default='Assistant Guide', max_length=50)),
                ('salary_rate', models.IntegerField(blank=True, null=True)),
                ('salary_days', models.IntegerField(blank=True, null=True)),
                ('count', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='trekkingexpense',
            name='guide_count',
        ),
        migrations.RemoveField(
            model_name='trekkingexpense',
            name='guide_name',
        ),
        migrations.DeleteModel(
            name='Guide',
        ),
        migrations.AddField(
            model_name='assistantguide',
            name='trekking_expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_guides', to='treks.trekkingexpense'),
        ),
    ]
