# Generated by Django 4.2.20 on 2025-04-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0006_assistantguide_remove_trekkingexpense_guide_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trekkingexpense',
            name='guide_advance_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trekkingexpense',
            name='misc_advance_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trekkingexpense',
            name='package_advance_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trekkingexpense',
            name='porter_advance_amount',
            field=models.IntegerField(default=0),
        ),
    ]
