# Generated by Django 4.2.20 on 2025-04-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0007_trekkingexpense_guide_advance_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trekkingexpense',
            name='assistant_advance_remark',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='trekkingexpense',
            name='guide_advance_remark',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='trekkingexpense',
            name='misc_advance_remark',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='trekkingexpense',
            name='package_advance_remark',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='trekkingexpense',
            name='porter_advance_remark',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
