# Generated by Django 4.2.20 on 2025-04-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0008_trekkingexpense_assistant_advance_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trekkingexpense',
            name='assistant_guide_amount',
            field=models.IntegerField(default=0),
        ),
    ]
